# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/niels/ClionProjects/Spin

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/niels/ClionProjects/Spin

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running interactive CMake command-line interface..."
	/usr/bin/cmake -i .
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/niels/ClionProjects/Spin/CMakeFiles /home/niels/ClionProjects/Spin/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/niels/ClionProjects/Spin/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Spin

# Build rule for target.
Spin: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Spin
.PHONY : Spin

# fast build rule for target.
Spin/fast:
	$(MAKE) -f CMakeFiles/Spin.dir/build.make CMakeFiles/Spin.dir/build
.PHONY : Spin/fast

BluetoothHandler.o: BluetoothHandler.cpp.o
.PHONY : BluetoothHandler.o

# target to build an object file
BluetoothHandler.cpp.o:
	$(MAKE) -f CMakeFiles/Spin.dir/build.make CMakeFiles/Spin.dir/BluetoothHandler.cpp.o
.PHONY : BluetoothHandler.cpp.o

BluetoothHandler.i: BluetoothHandler.cpp.i
.PHONY : BluetoothHandler.i

# target to preprocess a source file
BluetoothHandler.cpp.i:
	$(MAKE) -f CMakeFiles/Spin.dir/build.make CMakeFiles/Spin.dir/BluetoothHandler.cpp.i
.PHONY : BluetoothHandler.cpp.i

BluetoothHandler.s: BluetoothHandler.cpp.s
.PHONY : BluetoothHandler.s

# target to generate assembly for a file
BluetoothHandler.cpp.s:
	$(MAKE) -f CMakeFiles/Spin.dir/build.make CMakeFiles/Spin.dir/BluetoothHandler.cpp.s
.PHONY : BluetoothHandler.cpp.s

Commands/ICommand.o: Commands/ICommand.cpp.o
.PHONY : Commands/ICommand.o

# target to build an object file
Commands/ICommand.cpp.o:
	$(MAKE) -f CMakeFiles/Spin.dir/build.make CMakeFiles/Spin.dir/Commands/ICommand.cpp.o
.PHONY : Commands/ICommand.cpp.o

Commands/ICommand.i: Commands/ICommand.cpp.i
.PHONY : Commands/ICommand.i

# target to preprocess a source file
Commands/ICommand.cpp.i:
	$(MAKE) -f CMakeFiles/Spin.dir/build.make CMakeFiles/Spin.dir/Commands/ICommand.cpp.i
.PHONY : Commands/ICommand.cpp.i

Commands/ICommand.s: Commands/ICommand.cpp.s
.PHONY : Commands/ICommand.s

# target to generate assembly for a file
Commands/ICommand.cpp.s:
	$(MAKE) -f CMakeFiles/Spin.dir/build.make CMakeFiles/Spin.dir/Commands/ICommand.cpp.s
.PHONY : Commands/ICommand.cpp.s

Commands/WalkCommand.o: Commands/WalkCommand.cpp.o
.PHONY : Commands/WalkCommand.o

# target to build an object file
Commands/WalkCommand.cpp.o:
	$(MAKE) -f CMakeFiles/Spin.dir/build.make CMakeFiles/Spin.dir/Commands/WalkCommand.cpp.o
.PHONY : Commands/WalkCommand.cpp.o

Commands/WalkCommand.i: Commands/WalkCommand.cpp.i
.PHONY : Commands/WalkCommand.i

# target to preprocess a source file
Commands/WalkCommand.cpp.i:
	$(MAKE) -f CMakeFiles/Spin.dir/build.make CMakeFiles/Spin.dir/Commands/WalkCommand.cpp.i
.PHONY : Commands/WalkCommand.cpp.i

Commands/WalkCommand.s: Commands/WalkCommand.cpp.s
.PHONY : Commands/WalkCommand.s

# target to generate assembly for a file
Commands/WalkCommand.cpp.s:
	$(MAKE) -f CMakeFiles/Spin.dir/build.make CMakeFiles/Spin.dir/Commands/WalkCommand.cpp.s
.PHONY : Commands/WalkCommand.cpp.s

Controller.o: Controller.cpp.o
.PHONY : Controller.o

# target to build an object file
Controller.cpp.o:
	$(MAKE) -f CMakeFiles/Spin.dir/build.make CMakeFiles/Spin.dir/Controller.cpp.o
.PHONY : Controller.cpp.o

Controller.i: Controller.cpp.i
.PHONY : Controller.i

# target to preprocess a source file
Controller.cpp.i:
	$(MAKE) -f CMakeFiles/Spin.dir/build.make CMakeFiles/Spin.dir/Controller.cpp.i
.PHONY : Controller.cpp.i

Controller.s: Controller.cpp.s
.PHONY : Controller.s

# target to generate assembly for a file
Controller.cpp.s:
	$(MAKE) -f CMakeFiles/Spin.dir/build.make CMakeFiles/Spin.dir/Controller.cpp.s
.PHONY : Controller.cpp.s

Models/Leg.o: Models/Leg.cpp.o
.PHONY : Models/Leg.o

# target to build an object file
Models/Leg.cpp.o:
	$(MAKE) -f CMakeFiles/Spin.dir/build.make CMakeFiles/Spin.dir/Models/Leg.cpp.o
.PHONY : Models/Leg.cpp.o

Models/Leg.i: Models/Leg.cpp.i
.PHONY : Models/Leg.i

# target to preprocess a source file
Models/Leg.cpp.i:
	$(MAKE) -f CMakeFiles/Spin.dir/build.make CMakeFiles/Spin.dir/Models/Leg.cpp.i
.PHONY : Models/Leg.cpp.i

Models/Leg.s: Models/Leg.cpp.s
.PHONY : Models/Leg.s

# target to generate assembly for a file
Models/Leg.cpp.s:
	$(MAKE) -f CMakeFiles/Spin.dir/build.make CMakeFiles/Spin.dir/Models/Leg.cpp.s
.PHONY : Models/Leg.cpp.s

Models/SensorData.o: Models/SensorData.cpp.o
.PHONY : Models/SensorData.o

# target to build an object file
Models/SensorData.cpp.o:
	$(MAKE) -f CMakeFiles/Spin.dir/build.make CMakeFiles/Spin.dir/Models/SensorData.cpp.o
.PHONY : Models/SensorData.cpp.o

Models/SensorData.i: Models/SensorData.cpp.i
.PHONY : Models/SensorData.i

# target to preprocess a source file
Models/SensorData.cpp.i:
	$(MAKE) -f CMakeFiles/Spin.dir/build.make CMakeFiles/Spin.dir/Models/SensorData.cpp.i
.PHONY : Models/SensorData.cpp.i

Models/SensorData.s: Models/SensorData.cpp.s
.PHONY : Models/SensorData.s

# target to generate assembly for a file
Models/SensorData.cpp.s:
	$(MAKE) -f CMakeFiles/Spin.dir/build.make CMakeFiles/Spin.dir/Models/SensorData.cpp.s
.PHONY : Models/SensorData.cpp.s

Models/Servo.o: Models/Servo.cpp.o
.PHONY : Models/Servo.o

# target to build an object file
Models/Servo.cpp.o:
	$(MAKE) -f CMakeFiles/Spin.dir/build.make CMakeFiles/Spin.dir/Models/Servo.cpp.o
.PHONY : Models/Servo.cpp.o

Models/Servo.i: Models/Servo.cpp.i
.PHONY : Models/Servo.i

# target to preprocess a source file
Models/Servo.cpp.i:
	$(MAKE) -f CMakeFiles/Spin.dir/build.make CMakeFiles/Spin.dir/Models/Servo.cpp.i
.PHONY : Models/Servo.cpp.i

Models/Servo.s: Models/Servo.cpp.s
.PHONY : Models/Servo.s

# target to generate assembly for a file
Models/Servo.cpp.s:
	$(MAKE) -f CMakeFiles/Spin.dir/build.make CMakeFiles/Spin.dir/Models/Servo.cpp.s
.PHONY : Models/Servo.cpp.s

Monitor.o: Monitor.cpp.o
.PHONY : Monitor.o

# target to build an object file
Monitor.cpp.o:
	$(MAKE) -f CMakeFiles/Spin.dir/build.make CMakeFiles/Spin.dir/Monitor.cpp.o
.PHONY : Monitor.cpp.o

Monitor.i: Monitor.cpp.i
.PHONY : Monitor.i

# target to preprocess a source file
Monitor.cpp.i:
	$(MAKE) -f CMakeFiles/Spin.dir/build.make CMakeFiles/Spin.dir/Monitor.cpp.i
.PHONY : Monitor.cpp.i

Monitor.s: Monitor.cpp.s
.PHONY : Monitor.s

# target to generate assembly for a file
Monitor.cpp.s:
	$(MAKE) -f CMakeFiles/Spin.dir/build.make CMakeFiles/Spin.dir/Monitor.cpp.s
.PHONY : Monitor.cpp.s

Movements/DefaultMovement.o: Movements/DefaultMovement.cpp.o
.PHONY : Movements/DefaultMovement.o

# target to build an object file
Movements/DefaultMovement.cpp.o:
	$(MAKE) -f CMakeFiles/Spin.dir/build.make CMakeFiles/Spin.dir/Movements/DefaultMovement.cpp.o
.PHONY : Movements/DefaultMovement.cpp.o

Movements/DefaultMovement.i: Movements/DefaultMovement.cpp.i
.PHONY : Movements/DefaultMovement.i

# target to preprocess a source file
Movements/DefaultMovement.cpp.i:
	$(MAKE) -f CMakeFiles/Spin.dir/build.make CMakeFiles/Spin.dir/Movements/DefaultMovement.cpp.i
.PHONY : Movements/DefaultMovement.cpp.i

Movements/DefaultMovement.s: Movements/DefaultMovement.cpp.s
.PHONY : Movements/DefaultMovement.s

# target to generate assembly for a file
Movements/DefaultMovement.cpp.s:
	$(MAKE) -f CMakeFiles/Spin.dir/build.make CMakeFiles/Spin.dir/Movements/DefaultMovement.cpp.s
.PHONY : Movements/DefaultMovement.cpp.s

Movements/IMovement.o: Movements/IMovement.cpp.o
.PHONY : Movements/IMovement.o

# target to build an object file
Movements/IMovement.cpp.o:
	$(MAKE) -f CMakeFiles/Spin.dir/build.make CMakeFiles/Spin.dir/Movements/IMovement.cpp.o
.PHONY : Movements/IMovement.cpp.o

Movements/IMovement.i: Movements/IMovement.cpp.i
.PHONY : Movements/IMovement.i

# target to preprocess a source file
Movements/IMovement.cpp.i:
	$(MAKE) -f CMakeFiles/Spin.dir/build.make CMakeFiles/Spin.dir/Movements/IMovement.cpp.i
.PHONY : Movements/IMovement.cpp.i

Movements/IMovement.s: Movements/IMovement.cpp.s
.PHONY : Movements/IMovement.s

# target to generate assembly for a file
Movements/IMovement.cpp.s:
	$(MAKE) -f CMakeFiles/Spin.dir/build.make CMakeFiles/Spin.dir/Movements/IMovement.cpp.s
.PHONY : Movements/IMovement.cpp.s

ServerHandler.o: ServerHandler.cpp.o
.PHONY : ServerHandler.o

# target to build an object file
ServerHandler.cpp.o:
	$(MAKE) -f CMakeFiles/Spin.dir/build.make CMakeFiles/Spin.dir/ServerHandler.cpp.o
.PHONY : ServerHandler.cpp.o

ServerHandler.i: ServerHandler.cpp.i
.PHONY : ServerHandler.i

# target to preprocess a source file
ServerHandler.cpp.i:
	$(MAKE) -f CMakeFiles/Spin.dir/build.make CMakeFiles/Spin.dir/ServerHandler.cpp.i
.PHONY : ServerHandler.cpp.i

ServerHandler.s: ServerHandler.cpp.s
.PHONY : ServerHandler.s

# target to generate assembly for a file
ServerHandler.cpp.s:
	$(MAKE) -f CMakeFiles/Spin.dir/build.make CMakeFiles/Spin.dir/ServerHandler.cpp.s
.PHONY : ServerHandler.cpp.s

ServoDriver.o: ServoDriver.cpp.o
.PHONY : ServoDriver.o

# target to build an object file
ServoDriver.cpp.o:
	$(MAKE) -f CMakeFiles/Spin.dir/build.make CMakeFiles/Spin.dir/ServoDriver.cpp.o
.PHONY : ServoDriver.cpp.o

ServoDriver.i: ServoDriver.cpp.i
.PHONY : ServoDriver.i

# target to preprocess a source file
ServoDriver.cpp.i:
	$(MAKE) -f CMakeFiles/Spin.dir/build.make CMakeFiles/Spin.dir/ServoDriver.cpp.i
.PHONY : ServoDriver.cpp.i

ServoDriver.s: ServoDriver.cpp.s
.PHONY : ServoDriver.s

# target to generate assembly for a file
ServoDriver.cpp.s:
	$(MAKE) -f CMakeFiles/Spin.dir/build.make CMakeFiles/Spin.dir/ServoDriver.cpp.s
.PHONY : ServoDriver.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/Spin.dir/build.make CMakeFiles/Spin.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/Spin.dir/build.make CMakeFiles/Spin.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/Spin.dir/build.make CMakeFiles/Spin.dir/main.cpp.s
.PHONY : main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... Spin"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... BluetoothHandler.o"
	@echo "... BluetoothHandler.i"
	@echo "... BluetoothHandler.s"
	@echo "... Commands/ICommand.o"
	@echo "... Commands/ICommand.i"
	@echo "... Commands/ICommand.s"
	@echo "... Commands/WalkCommand.o"
	@echo "... Commands/WalkCommand.i"
	@echo "... Commands/WalkCommand.s"
	@echo "... Controller.o"
	@echo "... Controller.i"
	@echo "... Controller.s"
	@echo "... Models/Leg.o"
	@echo "... Models/Leg.i"
	@echo "... Models/Leg.s"
	@echo "... Models/SensorData.o"
	@echo "... Models/SensorData.i"
	@echo "... Models/SensorData.s"
	@echo "... Models/Servo.o"
	@echo "... Models/Servo.i"
	@echo "... Models/Servo.s"
	@echo "... Monitor.o"
	@echo "... Monitor.i"
	@echo "... Monitor.s"
	@echo "... Movements/DefaultMovement.o"
	@echo "... Movements/DefaultMovement.i"
	@echo "... Movements/DefaultMovement.s"
	@echo "... Movements/IMovement.o"
	@echo "... Movements/IMovement.i"
	@echo "... Movements/IMovement.s"
	@echo "... ServerHandler.o"
	@echo "... ServerHandler.i"
	@echo "... ServerHandler.s"
	@echo "... ServoDriver.o"
	@echo "... ServoDriver.i"
	@echo "... ServoDriver.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

